name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: list
        continue-on-error: true
        shell: pwsh
        run: |
          Get-ChildItem c:\Users\installer

      - name: installer
        continue-on-error: true
        shell: pwsh
        run: |
          Get-ChildItem c:\Users\installer | Measure-Object -Sum Length | Select-Object Count, Sum

