name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: list
        shell: pwsh
        run: |
          Get-ChildItem ${env:TEMP}\1

      - name: installer
        shell: pwsh
        run: |
          (Get-ChildItem c:\Users\installer -Recurse -File | Measure-Object -Sum Length | Select-Object Count, Sum)

